services:
  - type: web
    name: sentiment-analysis-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: OPENAI_API_KEY
        sync: false  # Set this in the Render dashboard
      - key: ALLOWED_ORIGINS
        value: https://frontend-portfolio-aomn.onrender.com/
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: PORT
        value: 10000
    dependencies:
      - type: redis
        name: sentiment-analysis-redis
        ipAllowList: []  # Only allow internal connections
