services:
  - type: web
    name: sentiment-analysis-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: OPENAI_API_KEY
        sync: false  # Set this in the Render dashboard
      - key: ALLOWED_ORIGINS
        value: https://frontend-portfolio-aomn.onrender.com,https://deerk-portfolio.onrender.com
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: starter
    healthCheckPath: /
    domains:
      - sentiment-analysis-service.onrender.com
    dependencies:
      - type: redis
        name: sentiment-analysis-redis
        ipAllowList: []  # Only allow internal connections
